# Generated by Django 5.2.1 on 2026-03-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_user_is_staff_user_is_superuser_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('full_time', 'Tiempo Completo'), ('part_time', 'Medio Tiempo'), ('internship', 'Práctica'), ('contract', 'Contrato')], max_length=20)),
                ('modality', models.CharField(choices=[('presential', 'Presencial'), ('remote', 'Remoto'), ('hybrid', 'Híbrido')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.canton')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='authentication.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.province')),
            ],
            options={
                'db_table': 'vacancy',
            },
        ),
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.category')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacancies.vacancy')),
            ],
            options={
                'db_table': 'vacancy_category',
                'unique_together': {('vacancy', 'category')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='categories',
            field=models.ManyToManyField(blank=True, through='Vacancies.VacancyCategory', to='common.category'),
        ),
        migrations.CreateModel(
            name='VacancyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.requirement')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vacancies.vacancy')),
            ],
            options={
                'db_table': 'vacancy_requirement',
                'unique_together': {('vacancy', 'requirement')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(blank=True, through='Vacancies.VacancyRequirement', to='common.requirement'),
        ),
    ]
