# Generated by Django 5.2.1 on 2026-03-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='starts_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
