# Generated by Django 5.2.1 on 2026-03-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Usuario'), ('company', 'Empresa'), ('institution', 'Institución'), ('system', 'Sistema')], max_length=20)),
                ('sender_id', models.PositiveIntegerField(blank=True, null=True)),
                ('receiver_type', models.CharField(choices=[('user', 'Usuario'), ('company', 'Empresa'), ('institution', 'Institución'), ('system', 'Sistema')], max_length=20)),
                ('receiver_id', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
