# Generated by Django 5.2.1 on 2026-03-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documents', '0002_document_multi_entity_and_images'),
        ('authentication', '0003_user_is_staff_user_is_superuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'external_links',
            },
        ),
        migrations.CreateModel(
            name='CompanyExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_external_links', to='authentication.company')),
                ('external_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_external_links', to='Profiles.externallink')),
            ],
            options={
                'db_table': 'company_external_links',
            },
        ),
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_formacion', models.CharField(blank=True, max_length=200)),
                ('carrera', models.CharField(blank=True, max_length=200)),
                ('nivel', models.CharField(blank=True, max_length=100)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_fields', to='Documents.document')),
            ],
            options={
                'db_table': 'profile_fields',
            },
        ),
        migrations.CreateModel(
            name='UserProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_fields', to='Profiles.profilefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_fields',
            },
        ),
    ]
