# Generated by Django 5.2.1 on 2026-03-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefield',
            old_name='nivel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='profilefield',
            old_name='carrera',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='profilefield',
            old_name='centro_formacion',
            new_name='training_center',
        ),
    ]
