# Generated by Django 5.2.1 on 2026-03-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_rename_nivel_profilefield_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefield',
            old_name='major',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='profilefield',
            old_name='level',
            new_name='educational_level',
        ),
    ]
