# Generated by Django 5.2.1 on 2026-03-03 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_rename_major_profilefield_degree_and_more'),
        ('authentication', '0005_seed_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='authentication.institutionformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institution_invitation',
                'unique_together': {('institution', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserInstitutionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='authentication.institutionformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_institution_formation',
                'unique_together': {('user', 'institution')},
            },
        ),
    ]
