# Generated by Django 5.2.1 on 2026-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionformation',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
