# Generated by Django 5.2.1 on 2026-03-02 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documents', '0001_initial'),
        ('Vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'postulation_status',
            },
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, help_text='CV adjunto al momento de postular', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to='Vacancies.vacancy')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Postulations.postulationstatus')),
            ],
            options={
                'db_table': 'postulation',
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
