from django.core.management.base import BaseCommand
from django.db import transaction

from apps.authentication.models import AvailabilityStatus, Role
from apps.common.models import Canton, Category, Currency, Province, Requirement
from apps.Postulations.models import PostulationStatus


ROLES = [
    {"id": 1, "name": "Administrador"},
    {"id": 2, "name": "Aspirante"},
    {"id": 3, "name": "Practicante"},
    {"id": 4, "name": "Empresa"},
    {"id": 5, "name": "Institucion de formacion"},
]

AVAILABILITY_STATUSES = [
    {"id": 1, "name": "En búsqueda de empleo", "is_available": True},
    {"id": 2, "name": "Abierto a oportunidades", "is_available": True},
    {"id": 3, "name": "No disponible", "is_available": False},
    {"id": 4, "name": "NA", "is_available": False},
]

POSTULATION_STATUSES = [
    {"id": 1, "name": "pendiente"},
    {"id": 2, "name": "leída"},
    {"id": 3, "name": "aceptada"},
    {"id": 4, "name": "rechazada"},
]

CURRENCIES = [
    {"id": 1, "name": "Colones", "symbol": "₡"},
    {"id": 2, "name": "Dólares", "symbol": "$"},
]

CATEGORIES = [
    {"id": 1,  "name": "Tecnología / Desarrollo de Software"},
    {"id": 2,  "name": "Sistemas / Infraestructura / DevOps"},
    {"id": 3,  "name": "Datos / BI / Analítica"},
    {"id": 4,  "name": "Seguridad / Ciberseguridad / Compliance TI"},
    {"id": 5,  "name": "Producto / Product Management"},
    {"id": 6,  "name": "Diseño / UX/UI"},
    {"id": 7,  "name": "Operaciones / Procesos"},
    {"id": 8,  "name": "Logística / Supply Chain / Inventario"},
    {"id": 9,  "name": "Compras / Procurement / Abastecimiento"},
    {"id": 10, "name": "Calidad / QA / Mejora Continua"},
    {"id": 11, "name": "Finanzas / Contabilidad"},
    {"id": 12, "name": "Riesgo / Auditoría / Control Interno"},
    {"id": 13, "name": "Ventas / Comercial"},
    {"id": 14, "name": "Marketing / Growth"},
    {"id": 15, "name": "Atención al Cliente / Soporte / Servicio"},
    {"id": 16, "name": "Recursos Humanos / Talento"},
    {"id": 17, "name": "Legal / Jurídico"},
    {"id": 18, "name": "Administración / Dirección / Gestión"},
    {"id": 19, "name": "Soft Skills (Habilidades Blandas)"},
]

PROVINCES = [
    {"id": 1, "name": "San José"},
    {"id": 2, "name": "Alajuela"},
    {"id": 3, "name": "Cartago"},
    {"id": 4, "name": "Heredia"},
    {"id": 5, "name": "Guanacaste"},
    {"id": 6, "name": "Puntarenas"},
    {"id": 7, "name": "Limón"},
]

CANTONS = [
    {"id": 1,  "province_id": 1, "name": "San José"},
    {"id": 2,  "province_id": 1, "name": "Escazú"},
    {"id": 3,  "province_id": 1, "name": "Desamparados"},
    {"id": 4,  "province_id": 1, "name": "Puriscal"},
    {"id": 5,  "province_id": 1, "name": "Tarrazú"},
    {"id": 6,  "province_id": 1, "name": "Aserrí"},
    {"id": 7,  "province_id": 1, "name": "Mora"},
    {"id": 8,  "province_id": 1, "name": "Goicoechea"},
    {"id": 9,  "province_id": 1, "name": "Santa Ana"},
    {"id": 10, "province_id": 1, "name": "Alajuelita"},
    {"id": 11, "province_id": 1, "name": "Vásquez de Coronado"},
    {"id": 12, "province_id": 1, "name": "Acosta"},
    {"id": 13, "province_id": 1, "name": "Tibás"},
    {"id": 14, "province_id": 1, "name": "Moravia"},
    {"id": 15, "province_id": 1, "name": "Montes de Oca"},
    {"id": 16, "province_id": 1, "name": "Turrubares"},
    {"id": 17, "province_id": 1, "name": "Dota"},
    {"id": 18, "province_id": 1, "name": "Curridabat"},
    {"id": 19, "province_id": 1, "name": "Pérez Zeledón"},
    {"id": 20, "province_id": 1, "name": "León Cortés Castro"},
    {"id": 21, "province_id": 2, "name": "Alajuela"},
    {"id": 22, "province_id": 2, "name": "San Ramón"},
    {"id": 23, "province_id": 2, "name": "Grecia"},
    {"id": 24, "province_id": 2, "name": "San Mateo"},
    {"id": 25, "province_id": 2, "name": "Atenas"},
    {"id": 26, "province_id": 2, "name": "Naranjo"},
    {"id": 27, "province_id": 2, "name": "Palmares"},
    {"id": 28, "province_id": 2, "name": "Poás"},
    {"id": 29, "province_id": 2, "name": "Orotina"},
    {"id": 30, "province_id": 2, "name": "San Carlos"},
    {"id": 31, "province_id": 2, "name": "Zarcero"},
    {"id": 32, "province_id": 2, "name": "Sarchí"},
    {"id": 33, "province_id": 2, "name": "Upala"},
    {"id": 34, "province_id": 2, "name": "Los Chiles"},
    {"id": 35, "province_id": 2, "name": "Guatuso"},
    {"id": 36, "province_id": 2, "name": "Río Cuarto"},
    {"id": 37, "province_id": 3, "name": "Cartago"},
    {"id": 38, "province_id": 3, "name": "Paraíso"},
    {"id": 39, "province_id": 3, "name": "La Unión"},
    {"id": 40, "province_id": 3, "name": "Jiménez"},
    {"id": 41, "province_id": 3, "name": "Turrialba"},
    {"id": 42, "province_id": 3, "name": "Alvarado"},
    {"id": 43, "province_id": 3, "name": "Oreamuno"},
    {"id": 44, "province_id": 3, "name": "El Guarco"},
    {"id": 45, "province_id": 4, "name": "Heredia"},
    {"id": 46, "province_id": 4, "name": "Barva"},
    {"id": 47, "province_id": 4, "name": "Santo Domingo"},
    {"id": 48, "province_id": 4, "name": "Santa Bárbara"},
    {"id": 49, "province_id": 4, "name": "San Rafael"},
    {"id": 50, "province_id": 4, "name": "San Isidro"},
    {"id": 51, "province_id": 4, "name": "Belén"},
    {"id": 52, "province_id": 4, "name": "Flores"},
    {"id": 53, "province_id": 4, "name": "San Pablo"},
    {"id": 54, "province_id": 4, "name": "Sarapiquí"},
    {"id": 55, "province_id": 5, "name": "Liberia"},
    {"id": 56, "province_id": 5, "name": "Nicoya"},
    {"id": 57, "province_id": 5, "name": "Santa Cruz"},
    {"id": 58, "province_id": 5, "name": "Bagaces"},
    {"id": 59, "province_id": 5, "name": "Carrillo"},
    {"id": 60, "province_id": 5, "name": "Cañas"},
    {"id": 61, "province_id": 5, "name": "Abangares"},
    {"id": 62, "province_id": 5, "name": "Tilarán"},
    {"id": 63, "province_id": 5, "name": "Nandayure"},
    {"id": 64, "province_id": 5, "name": "La Cruz"},
    {"id": 65, "province_id": 5, "name": "Hojancha"},
    {"id": 66, "province_id": 6, "name": "Puntarenas"},
    {"id": 67, "province_id": 6, "name": "Esparza"},
    {"id": 68, "province_id": 6, "name": "Buenos Aires"},
    {"id": 69, "province_id": 6, "name": "Montes de Oro"},
    {"id": 70, "province_id": 6, "name": "Osa"},
    {"id": 71, "province_id": 6, "name": "Quepos"},
    {"id": 72, "province_id": 6, "name": "Golfito"},
    {"id": 73, "province_id": 6, "name": "Coto Brus"},
    {"id": 74, "province_id": 6, "name": "Parrita"},
    {"id": 75, "province_id": 6, "name": "Corredores"},
    {"id": 76, "province_id": 6, "name": "Garabito"},
    {"id": 77, "province_id": 6, "name": "Monteverde"},
    {"id": 78, "province_id": 6, "name": "Puerto Jiménez"},
    {"id": 79, "province_id": 7, "name": "Limón"},
    {"id": 80, "province_id": 7, "name": "Pococí"},
    {"id": 81, "province_id": 7, "name": "Siquirres"},
    {"id": 82, "province_id": 7, "name": "Talamanca"},
    {"id": 83, "province_id": 7, "name": "Matina"},
    {"id": 84, "province_id": 7, "name": "Guácimo"},
]

REQUIREMENTS = [
    # 1) Tecnología / Desarrollo de Software
    {"id": 1,   "name": "JavaScript",                          "category_id": 1},
    {"id": 2,   "name": "TypeScript",                          "category_id": 1},
    {"id": 3,   "name": "HTML",                                "category_id": 1},
    {"id": 4,   "name": "CSS",                                 "category_id": 1},
    {"id": 5,   "name": "React",                               "category_id": 1},
    {"id": 6,   "name": "Next.js",                             "category_id": 1},
    {"id": 7,   "name": "Node.js",                             "category_id": 1},
    {"id": 8,   "name": "Express.js",                          "category_id": 1},
    {"id": 9,   "name": "Python",                              "category_id": 1},
    {"id": 10,  "name": "Django",                              "category_id": 1},
    {"id": 11,  "name": "Django REST Framework",               "category_id": 1},
    {"id": 12,  "name": "FastAPI",                             "category_id": 1},
    {"id": 13,  "name": "Java",                                "category_id": 1},
    {"id": 14,  "name": "Spring Boot",                         "category_id": 1},
    {"id": 15,  "name": "C#",                                  "category_id": 1},
    {"id": 16,  "name": ".NET",                                "category_id": 1},
    {"id": 17,  "name": "Go",                                  "category_id": 1},
    {"id": 18,  "name": "PHP",                                 "category_id": 1},
    {"id": 19,  "name": "Laravel",                             "category_id": 1},
    {"id": 20,  "name": "Ruby on Rails",                       "category_id": 1},
    {"id": 21,  "name": "REST APIs",                           "category_id": 1},
    {"id": 22,  "name": "GraphQL",                             "category_id": 1},
    {"id": 23,  "name": "OpenAPI/Swagger",                     "category_id": 1},
    {"id": 24,  "name": "Arquitectura de Software",            "category_id": 1},
    {"id": 25,  "name": "Patrones de Diseño",                  "category_id": 1},
    {"id": 26,  "name": "Diseño de Microservicios",            "category_id": 1},
    {"id": 27,  "name": "Integraciones de terceros (APIs)",    "category_id": 1},
    {"id": 28,  "name": "Autenticación (OAuth2)",              "category_id": 1},
    {"id": 29,  "name": "JWT",                                 "category_id": 1},
    {"id": 30,  "name": "Testing Unitario",                    "category_id": 1},
    {"id": 31,  "name": "Testing de Integración",              "category_id": 1},
    {"id": 32,  "name": "Jest",                                "category_id": 1},
    {"id": 33,  "name": "Cypress",                             "category_id": 1},
    {"id": 34,  "name": "Playwright",                          "category_id": 1},
    {"id": 35,  "name": "Git",                                 "category_id": 1},
    {"id": 36,  "name": "Code Review",                         "category_id": 1},
    {"id": 37,  "name": "Refactorización",                     "category_id": 1},
    # 2) Sistemas / Infraestructura / DevOps
    {"id": 38,  "name": "Linux",                               "category_id": 2},
    {"id": 39,  "name": "Bash/Shell Scripting",                "category_id": 2},
    {"id": 40,  "name": "Docker",                              "category_id": 2},
    {"id": 41,  "name": "Docker Compose",                      "category_id": 2},
    {"id": 42,  "name": "Kubernetes",                          "category_id": 2},
    {"id": 43,  "name": "Nginx",                               "category_id": 2},
    {"id": 44,  "name": "CI/CD",                               "category_id": 2},
    {"id": 45,  "name": "GitHub Actions",                      "category_id": 2},
    {"id": 46,  "name": "Terraform",                           "category_id": 2},
    {"id": 47,  "name": "AWS",                                 "category_id": 2},
    {"id": 48,  "name": "Google Cloud (GCP)",                  "category_id": 2},
    {"id": 49,  "name": "Azure",                               "category_id": 2},
    {"id": 50,  "name": "Monitoreo/Observabilidad",            "category_id": 2},
    {"id": 51,  "name": "Prometheus",                          "category_id": 2},
    {"id": 52,  "name": "Grafana",                             "category_id": 2},
    {"id": 53,  "name": "Sentry",                              "category_id": 2},
    {"id": 54,  "name": "Gestión de Incidentes",               "category_id": 2},
    {"id": 55,  "name": "Gestión de Cambios (IT)",             "category_id": 2},
    {"id": 56,  "name": "ITIL Foundations",                    "category_id": 2},
    {"id": 57,  "name": "Redes (Networking Fundamentals)",     "category_id": 2},
    {"id": 58,  "name": "Balanceo de carga",                   "category_id": 2},
    {"id": 59,  "name": "Backup & Recovery",                   "category_id": 2},
    # 3) Datos / BI / Analítica
    {"id": 60,  "name": "SQL",                                 "category_id": 3},
    {"id": 61,  "name": "PostgreSQL",                          "category_id": 3},
    {"id": 62,  "name": "MySQL",                               "category_id": 3},
    {"id": 63,  "name": "MongoDB",                             "category_id": 3},
    {"id": 64,  "name": "Redis",                               "category_id": 3},
    {"id": 65,  "name": "Modelado de Datos",                   "category_id": 3},
    {"id": 66,  "name": "ETL",                                 "category_id": 3},
    {"id": 67,  "name": "Data Warehousing",                    "category_id": 3},
    {"id": 68,  "name": "Power BI",                            "category_id": 3},
    {"id": 69,  "name": "Tableau",                             "category_id": 3},
    {"id": 70,  "name": "Excel",                               "category_id": 3},
    {"id": 71,  "name": "Google Sheets",                       "category_id": 3},
    {"id": 72,  "name": "Análisis de Datos",                   "category_id": 3},
    {"id": 73,  "name": "Visualización de Datos",              "category_id": 3},
    {"id": 74,  "name": "Diseño de KPIs",                      "category_id": 3},
    {"id": 75,  "name": "OKRs (seguimiento)",                  "category_id": 3},
    {"id": 76,  "name": "Data Governance",                     "category_id": 3},
    {"id": 77,  "name": "Calidad de Datos",                    "category_id": 3},
    {"id": 78,  "name": "A/B Testing",                         "category_id": 3},
    {"id": 79,  "name": "Pandas",                              "category_id": 3},
    {"id": 80,  "name": "BigQuery",                            "category_id": 3},
    {"id": 81,  "name": "Snowflake",                           "category_id": 3},
    # 4) Seguridad / Ciberseguridad / Compliance TI
    {"id": 82,  "name": "Seguridad de la Información (básico)", "category_id": 4},
    {"id": 83,  "name": "Gestión de Identidades (IAM)",        "category_id": 4},
    {"id": 84,  "name": "Principios de mínimo privilegio",     "category_id": 4},
    {"id": 85,  "name": "Control de accesos y roles (RBAC)",   "category_id": 4},
    {"id": 86,  "name": "Gestión de secretos",                 "category_id": 4},
    {"id": 87,  "name": "Hardening básico (servidores)",       "category_id": 4},
    {"id": 88,  "name": "Vulnerability Management",            "category_id": 4},
    {"id": 89,  "name": "OWASP Top 10",                        "category_id": 4},
    {"id": 90,  "name": "Seguridad en APIs",                   "category_id": 4},
    {"id": 91,  "name": "Data Privacy",                        "category_id": 4},
    {"id": 92,  "name": "GDPR (básico)",                       "category_id": 4},
    {"id": 93,  "name": "Políticas de seguridad",              "category_id": 4},
    # 5) Producto / Product Management
    {"id": 94,  "name": "Product Management",                  "category_id": 5},
    {"id": 95,  "name": "Roadmap",                             "category_id": 5},
    {"id": 96,  "name": "Gestión de Backlog",                  "category_id": 5},
    {"id": 97,  "name": "User Stories",                        "category_id": 5},
    {"id": 98,  "name": "Priorización (RICE/ICE/MoSCoW)",      "category_id": 5},
    {"id": 99,  "name": "Discovery",                           "category_id": 5},
    {"id": 100, "name": "Definición de MVP",                   "category_id": 5},
    {"id": 101, "name": "Product Analytics",                   "category_id": 5},
    {"id": 102, "name": "Gestión de Stakeholders",             "category_id": 5},
    {"id": 103, "name": "Documentación de Requerimientos",     "category_id": 5},
    # 6) Diseño / UX/UI
    {"id": 104, "name": "Figma",                               "category_id": 6},
    {"id": 105, "name": "Diseño UI",                           "category_id": 6},
    {"id": 106, "name": "Investigación UX",                    "category_id": 6},
    {"id": 107, "name": "Prototipado",                         "category_id": 6},
    {"id": 108, "name": "Design Systems",                      "category_id": 6},
    {"id": 109, "name": "Accesibilidad (WCAG)",                "category_id": 6},
    {"id": 110, "name": "Arquitectura de Información",         "category_id": 6},
    # 7) Operaciones / Procesos
    {"id": 111, "name": "Gestión de Operaciones",              "category_id": 7},
    {"id": 112, "name": "Mapeo de Procesos",                   "category_id": 7},
    {"id": 113, "name": "Documentación SOPs",                  "category_id": 7},
    {"id": 114, "name": "Mejora Continua",                     "category_id": 7},
    {"id": 115, "name": "Lean",                                "category_id": 7},
    {"id": 116, "name": "Análisis de causa raíz (RCA)",        "category_id": 7},
    {"id": 117, "name": "Gestión por KPIs (Operaciones)",      "category_id": 7},
    {"id": 118, "name": "Planificación de Capacidad",          "category_id": 7},
    {"id": 119, "name": "Business Continuity Planning",        "category_id": 7},
    {"id": 120, "name": "Gestión de Crisis",                   "category_id": 7},
    # 8) Logística / Supply Chain / Inventario
    {"id": 121, "name": "Supply Chain Management",             "category_id": 8},
    {"id": 122, "name": "Logística",                           "category_id": 8},
    {"id": 123, "name": "Gestión de Inventario",               "category_id": 8},
    {"id": 124, "name": "Operación de Bodega",                 "category_id": 8},
    {"id": 125, "name": "Planeación de Demanda",               "category_id": 8},
    {"id": 126, "name": "S&OP",                                "category_id": 8},
    {"id": 127, "name": "Ruteo / Distribución",                "category_id": 8},
    # 9) Compras / Procurement / Abastecimiento
    {"id": 128, "name": "Procurement",                         "category_id": 9},
    {"id": 129, "name": "Gestión de Proveedores",              "category_id": 9},
    {"id": 130, "name": "Negociación con Proveedores",         "category_id": 9},
    {"id": 131, "name": "Gestión de Contratos",                "category_id": 9},
    {"id": 132, "name": "Sourcing",                            "category_id": 9},
    {"id": 133, "name": "Análisis de costos (Compras)",        "category_id": 9},
    # 10) Calidad / QA / Mejora Continua
    {"id": 134, "name": "Quality Management",                  "category_id": 10},
    {"id": 135, "name": "Quality Assurance (QA)",              "category_id": 10},
    {"id": 136, "name": "Control de Calidad (QC)",             "category_id": 10},
    {"id": 137, "name": "Six Sigma (básico)",                  "category_id": 10},
    {"id": 138, "name": "KPIs de calidad",                     "category_id": 10},
    {"id": 139, "name": "Auditorías internas (calidad)",       "category_id": 10},
    # 11) Finanzas / Contabilidad
    {"id": 140, "name": "Análisis Financiero",                 "category_id": 11},
    {"id": 141, "name": "Presupuestación (Budgeting)",         "category_id": 11},
    {"id": 142, "name": "Forecasting",                         "category_id": 11},
    {"id": 143, "name": "Flujo de Caja",                       "category_id": 11},
    {"id": 144, "name": "P&L Management",                      "category_id": 11},
    {"id": 145, "name": "Contabilidad General",                "category_id": 11},
    {"id": 146, "name": "Cuentas por Pagar (AP)",              "category_id": 11},
    {"id": 147, "name": "Cuentas por Cobrar (AR)",             "category_id": 11},
    {"id": 148, "name": "Conciliación Bancaria",               "category_id": 11},
    {"id": 149, "name": "Planillas / Payroll",                 "category_id": 11},
    {"id": 150, "name": "Impuestos (cumplimiento)",            "category_id": 11},
    {"id": 151, "name": "IFRS (básico)",                       "category_id": 11},
    {"id": 152, "name": "Reportes Financieros",                "category_id": 11},
    {"id": 153, "name": "Análisis de variaciones",             "category_id": 11},
    {"id": 154, "name": "Estrategia de precios",               "category_id": 11},
    {"id": 155, "name": "Unit Economics",                      "category_id": 11},
    # 12) Riesgo / Auditoría / Control Interno
    {"id": 156, "name": "Control Interno",                     "category_id": 12},
    {"id": 157, "name": "Auditoría Interna",                   "category_id": 12},
    {"id": 158, "name": "Auditoría Externa (coordinación)",    "category_id": 12},
    {"id": 159, "name": "Preparación para auditoría",          "category_id": 12},
    {"id": 160, "name": "Gestión de Riesgos",                  "category_id": 12},
    {"id": 161, "name": "Prevención de Fraude",                "category_id": 12},
    {"id": 162, "name": "Compliance corporativo",              "category_id": 12},
    # 13) Ventas / Comercial
    {"id": 163, "name": "Estrategia de Ventas",                "category_id": 13},
    {"id": 164, "name": "Ventas B2B",                          "category_id": 13},
    {"id": 165, "name": "Ventas B2C",                          "category_id": 13},
    {"id": 166, "name": "Gestión de Cuentas (Account Management)", "category_id": 13},
    {"id": 167, "name": "Key Account Management",              "category_id": 13},
    {"id": 168, "name": "Gestión de Pipeline",                 "category_id": 13},
    {"id": 169, "name": "Prospección",                         "category_id": 13},
    {"id": 170, "name": "Cold Outreach",                       "category_id": 13},
    {"id": 171, "name": "Calificación de Leads",               "category_id": 13},
    {"id": 172, "name": "Técnicas de Cierre",                  "category_id": 13},
    {"id": 173, "name": "CRM",                                 "category_id": 13},
    {"id": 174, "name": "Salesforce",                          "category_id": 13},
    {"id": 175, "name": "HubSpot",                             "category_id": 13},
    {"id": 176, "name": "Customer Success",                    "category_id": 13},
    {"id": 177, "name": "Gestión de churn",                    "category_id": 13},
    {"id": 178, "name": "Upselling & Cross-selling",           "category_id": 13},
    # 14) Marketing / Growth
    {"id": 179, "name": "SEO",                                 "category_id": 14},
    {"id": 180, "name": "SEM",                                 "category_id": 14},
    {"id": 181, "name": "Google Ads",                          "category_id": 14},
    {"id": 182, "name": "Meta Ads",                            "category_id": 14},
    {"id": 183, "name": "Email Marketing",                     "category_id": 14},
    {"id": 184, "name": "Automatización de Marketing",         "category_id": 14},
    {"id": 185, "name": "Estrategia de Contenido",             "category_id": 14},
    {"id": 186, "name": "Copywriting",                         "category_id": 14},
    {"id": 187, "name": "Brand Management",                    "category_id": 14},
    {"id": 188, "name": "Market Research",                     "category_id": 14},
    {"id": 189, "name": "Análisis Competitivo",                "category_id": 14},
    {"id": 190, "name": "Go-to-Market (GTM)",                  "category_id": 14},
    {"id": 191, "name": "CRO (Optimización de conversión)",    "category_id": 14},
    {"id": 192, "name": "Gestión de Redes Sociales",           "category_id": 14},
    {"id": 193, "name": "PR (Relaciones Públicas)",            "category_id": 14},
    # 15) Atención al Cliente / Soporte / Servicio
    {"id": 194, "name": "Customer Support",                    "category_id": 15},
    {"id": 195, "name": "Gestión de Tickets",                  "category_id": 15},
    {"id": 196, "name": "Zendesk",                             "category_id": 15},
    {"id": 197, "name": "Intercom",                            "category_id": 15},
    {"id": 198, "name": "Gestión de Escalamientos",            "category_id": 15},
    {"id": 199, "name": "SLA Management",                      "category_id": 15},
    {"id": 200, "name": "Base de Conocimiento (Knowledge Base)", "category_id": 15},
    {"id": 201, "name": "Soporte Técnico",                     "category_id": 15},
    {"id": 202, "name": "Customer Experience (CX)",            "category_id": 15},
    # 16) Recursos Humanos / Talento
    {"id": 203, "name": "Reclutamiento",                       "category_id": 16},
    {"id": 204, "name": "Talent Acquisition",                  "category_id": 16},
    {"id": 205, "name": "Entrevistas",                         "category_id": 16},
    {"id": 206, "name": "Onboarding",                          "category_id": 16},
    {"id": 207, "name": "Gestión de desempeño",                "category_id": 16},
    {"id": 208, "name": "Compensación y Beneficios",           "category_id": 16},
    {"id": 209, "name": "Relaciones laborales",                "category_id": 16},
    {"id": 210, "name": "Capacitación y Desarrollo",           "category_id": 16},
    {"id": 211, "name": "Políticas de RRHH",                   "category_id": 16},
    # 17) Legal / Jurídico
    {"id": 212, "name": "Contratos (redacción y revisión)",    "category_id": 17},
    {"id": 213, "name": "Cumplimiento Legal",                  "category_id": 17},
    {"id": 214, "name": "Derecho Laboral (básico)",            "category_id": 17},
    {"id": 215, "name": "Protección de Datos",                 "category_id": 17},
    {"id": 216, "name": "Gobierno Corporativo",                "category_id": 17},
    {"id": 217, "name": "Gestión de políticas internas",       "category_id": 17},
    # 18) Administración / Dirección / Gestión
    {"id": 218, "name": "Project Management",                  "category_id": 18},
    {"id": 219, "name": "Gestión de Stakeholders",             "category_id": 18},
    {"id": 220, "name": "Gestión de Presupuesto",              "category_id": 18},
    {"id": 221, "name": "Gestión de Proyectos (Agile/Scrum)",  "category_id": 18},
    {"id": 222, "name": "Kanban",                              "category_id": 18},
    {"id": 223, "name": "Jira",                                "category_id": 18},
    {"id": 224, "name": "Confluence",                          "category_id": 18},
    {"id": 225, "name": "Notion",                              "category_id": 18},
    {"id": 226, "name": "Planeación Estratégica",              "category_id": 18},
    {"id": 227, "name": "Gestión de OKRs",                     "category_id": 18},
    {"id": 228, "name": "Reportes Ejecutivos",                 "category_id": 18},
    {"id": 229, "name": "Gestión de equipos",                  "category_id": 18},
    # 19) Soft Skills
    {"id": 230, "name": "Comunicación",                        "category_id": 19},
    {"id": 231, "name": "Trabajo en equipo",                   "category_id": 19},
    {"id": 232, "name": "Resolución de problemas",             "category_id": 19},
    {"id": 233, "name": "Pensamiento crítico",                 "category_id": 19},
    {"id": 234, "name": "Gestión del tiempo",                  "category_id": 19},
    {"id": 235, "name": "Adaptabilidad",                       "category_id": 19},
    {"id": 236, "name": "Liderazgo",                           "category_id": 19},
    {"id": 237, "name": "Proactividad",                        "category_id": 19},
    {"id": 238, "name": "Atención al detalle",                 "category_id": 19},
    {"id": 239, "name": "Orientación a resultados",            "category_id": 19},
    {"id": 240, "name": "Inteligencia emocional",              "category_id": 19},
    {"id": 241, "name": "Manejo de conflicto",                 "category_id": 19},
    {"id": 242, "name": "Negociación",                         "category_id": 19},
    {"id": 243, "name": "Escucha activa",                      "category_id": 19},
    {"id": 244, "name": "Empatía",                             "category_id": 19},
    {"id": 245, "name": "Accountability / Responsabilidad",    "category_id": 19},
    {"id": 246, "name": "Organización",                        "category_id": 19},
    {"id": 247, "name": "Tolerancia a la presión",             "category_id": 19},
    {"id": 248, "name": "Pensamiento estratégico",             "category_id": 19},
    {"id": 249, "name": "Comunicación escrita",                "category_id": 19},
    {"id": 250, "name": "Presentación / Oratoria",             "category_id": 19},
]


class Command(BaseCommand):
    help = "Inserta los datos auxiliares iniciales en la base de datos"

    def _seed(self, label, model, data, defaults_fn):
        created_count = 0
        for item in data:
            pk = item["id"]
            _, created = model.objects.update_or_create(
                id=pk,
                defaults=defaults_fn(item),
            )
            if created:
                created_count += 1
        self.stdout.write(f"  {label}: {len(data)} registros ({created_count} nuevos)")

    @transaction.atomic
    def handle(self, *args, **kwargs):
        self.stdout.write("Iniciando seed de datos auxiliares...\n")

        self._seed(
            "Roles",
            Role,
            ROLES,
            lambda r: {"name": r["name"]},
        )

        self._seed(
            "AvailabilityStatus",
            AvailabilityStatus,
            AVAILABILITY_STATUSES,
            lambda r: {"name": r["name"], "is_available": r["is_available"]},
        )

        self._seed(
            "PostulationStatus",
            PostulationStatus,
            POSTULATION_STATUSES,
            lambda r: {"name": r["name"]},
        )

        self._seed(
            "Currencies",
            Currency,
            CURRENCIES,
            lambda r: {"name": r["name"], "symbol": r["symbol"]},
        )

        self._seed(
            "Categories",
            Category,
            CATEGORIES,
            lambda r: {"name": r["name"]},
        )

        self._seed(
            "Provinces",
            Province,
            PROVINCES,
            lambda r: {"name": r["name"]},
        )

        self._seed(
            "Cantons",
            Canton,
            CANTONS,
            lambda r: {"province_id": r["province_id"], "name": r["name"]},
        )

        self._seed(
            "Requirements",
            Requirement,
            REQUIREMENTS,
            lambda r: {"category_id": r["category_id"], "name": r["name"]},
        )

        self.stdout.write(self.style.SUCCESS("\nSeed completado exitosamente."))
